# templates/06-backend-hpa.yaml
{{- if .Values.autoscaling.backend.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  # name will be "<release>-backend-hpa"
  name: {{ include "quote-app.fullname" . }}-backend-hpa
  # namespace comes from `-n` on helm install; don't hardcode
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    # matches your Deployment name: {{ include "quote-app.fullname" . }}-backend
    name: {{ include "quote-app.fullname" . }}-backend
  minReplicas: {{ .Values.autoscaling.backend.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.backend.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.backend.targetCPUUtilizationPercentage }}
{{- end }}
